### PR TITLE
Booleans

### PR DESCRIPTION
**Pull request by colinleach**
Vector `&`, `|` are excluded from `introduction.md`, mentioned in `about.md`.

Could probably improve `links.json`?

### CODE REVIEW

**Comment by colinleach** [comment]
More Git confusion: this and 3 other PRs (#254, #256, #257) have merge conflicts in `config.json`. Is there a simple way to fix this, or should I close the PRs and start again from a new base?

Newer PRs ($259, #260) seem to be OK, because they're not trying to be the only slug in their group.

**Comment by ErikSchierboom** [comment]
> More Git confusion: this and 3 other PRs (https://github.com/exercism/r/pull/254, https://github.com/exercism/r/pull/256, https://github.com/exercism/r/pull/257) have merge conflicts in config.json. Is there a simple way to fix this, or should I close the PRs and start again from a new base?

These are fairly easy to fix. Let's take an example:

```diff
<<<<<<< vehicle-purchase
        "slug": "vehicle-purchase",
        "name": "Vehicle Purchase",
        "uuid": "d40b31f7-6c0d-46fa-8bd6-6618464c2572",
        "concepts": [
          "conditionals"
        ],
        "prerequisites": [
          "booleans"
        ],
=======
        "slug": "lasagna",
        "name": "Lasagna",
        "uuid": "6fd75bbd-8654-4d6a-80b5-29344ceb8a48",
        "concepts": ["basics"],
        "prerequisites": [],
>>>>>>> main
        "status": "wip"
```

Basically, this is saying that the `"status": "wip"` part is shared by both.

1. Remove the `>>>>>>> main` line to have `"status": "wip"` be part of the second entry
2. Replace the `=======` line with three lines:
   1. `"status": "wip"`
   2. `},`
   3. `{`
4. Remove the `<<<<<<< vehicle-purchase` line

This should give you:

```
```diff
        "slug": "vehicle-purchase",
        "name": "Vehicle Purchase",
        "uuid": "d40b31f7-6c0d-46fa-8bd6-6618464c2572",
        "concepts": [
          "conditionals"
        ],
        "prerequisites": [
          "booleans"
        ],
        "status": "wip"
    },
    {
        "slug": "lasagna",
        "name": "Lasagna",
        "uuid": "6fd75bbd-8654-4d6a-80b5-29344ceb8a48",
        "concepts": ["basics"],
        "prerequisites": [],
        "status": "wip"
```

I've done one conflict for you, maybe you could try doing the others?

**Comment by colinleach** [comment]
Many thanks, Erik! All is good now.

**Review by jonmcalder — APPROVED** [review]
All good! (for now at least - maybe we'll think of improvements further down the line).

**Pull request merged**
