### PR TITLE
Basics  concept and Lasagna exercise

### PR DESCRIPTION
**Pull request by colinleach**
The Lasagna concept exercise was created by @jonmcalder : [PR #202](https://github.com/exercism/r/pull/202), dated January 2022. This remains unmerged as of April 2023 and is copied here for completeness.

This PR adds documentation to the exercise and adds the closely-related `basics` concept.

This double PR is a special case - I won't repeat this with others.

### CODE REVIEW

**Comment by colinleach** [comment]
CI failures seem to be because `armstrong-numbers` is incompatible with 3.6.3 (use of pipes). No obvious issues with this PR, I think?

@jonmcalder previously wondered out loud about wheher it's time to drop 3.6.3 support. Not my decision, but it might make life easier for everyone.

**Comment by jonmcalder** [comment]
Thanks @colinleach! Since part of this PR copies #202, would you be happy with that being merged first so that the diff for this PR (both what's added and what's changed if anything) is clearer? If so, please approve #202 for me and it can be merged as is.

The failing test on R 3.6.3 can be ignored for now - I agree that we can probably just drop the tests for R3.6.3 now as we'll likely want to start encouraging use of pipes going forward.

**Comment by colinleach** [comment]
Of course, whatever you think is best.

**Comment by jonmcalder** [comment]
Sorry for the hassle! And thanks again.

**Comment by colinleach** [comment]
Waiting till morning seems to be not quite enough for a successful rebase: there are still too many changed files in this PR. I think it may be easier to close it and start again with a PR from a clean base.

**Pull request closed without merging**
