### PR TITLE
All your base

### PR DESCRIPTION
**Pull request by colinleach**
Something to auto-close, for now.

Python, Julia, F# all agree difficulty 4. This feels about right.

### CODE REVIEW

**Review by jonmcalder — CHANGES_REQUESTED** [review]
This is great thanks!

Just a few length 1 vectors I'd prefer were cleaned up.

**Comment by colinleach** [comment]
Hmm, yes - first submitted last April, this was one of the first things I'd done in R for several years. It shows!

**Comment by colinleach** [comment]
I think I made the requested changes in https://github.com/exercism/r/pull/247/commits/6f053f494b1d9664c1aa1df025c1c5450a1118cf. Merging still blocked, so I assume you need to confirm it.

**Review by jonmcalder — APPROVED** [review]
Great!

**Pull request merged**
