### PR TITLE
Step down as maintainer

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hi @jonboiser & @jonmcalder,

I'm sorry that I didn't find any time to invest here for many months now. Hence, I don't feel good about calling myself maintainer here anymore.

We've gotten the track off the ground, and we can be proud of that :-)

Good luck with this track, and kind regards!
Katrin

### CODE REVIEW

**Comment by jonboiser** [comment]
Thanks for all your help @katrinleinweber! I think you will continue to be a maintainer as far GitHub permissions are concerned. I'll leave it up to someone else to properly off-board you in that regard.

**Comment by jonmcalder** [comment]
Hey @katrinleinweber! Sad to see you go, but I understand and am grateful for all the time, energy, effort and insight that you've invested both into the R track and into Exercism in general over the past 3 years. I'm sure we'll stay in touch!

**Comment by iHiD** [comment]
@katrinleinweber Very sorry to see you go too! If you every feel like you'd like to get back involved again, you'll always be welcome. Thank you for your contribution both in terms of this track but also into Exercism in general, and good luck with life :)

**Comment by kytrinyx** [comment]
@katrinleinweber Thank you so much for all the time and effort and attention and knowledge that you've poured into the R track and for being a lovely human being in the Exercism community. It has been such a pleasure having you here. Best of luck onwards!

**Comment by katrinleinweber** [comment]
Thank you all for the kind words, @jonboiser @jonmcalder @iHiD & @kytrinyx :-) All the best for your 2020s as well!

**Pull request merged**
