### PR TITLE
Add script to add practice exercise

### PR DESCRIPTION
**Pull request by ErikSchierboom**
I'm planning on maybe adding a couple of exercises, and this script helps (newer tracks get this for free: https://github.com/exercism/generic-track/blob/main/bin/add-practice-exercise)

### CODE REVIEW

**Review by jonmcalder — APPROVED** [review]
Thanks Erik! Have only checked / scanned this quickly from my phone for now so I'll want to actually test it out later but I approve nevertheless. Is the idea to keep this generic or to (optionally) tailor it further to each track?

**Comment by ErikSchierboom** [comment]
> Is the idea to keep this generic or to (optionally) tailor it further to each track?

It's a generic starting point, but each track should tweak it as they desire.

**Comment by ErikSchierboom** [comment]
I'll wait with merging until you've tested it.

**Comment by jonmcalder** [comment]
Thanks I have since run it and all looked good so I think we can merge.

**Pull request merged**
