### PR TITLE
Add crypto-square exercise

### PR DESCRIPTION
**Pull request by jonmcalder**
Implement tests and example solution
Generate README
Update config

### CODE REVIEW

**Comment by jonmcalder** [comment]
Following the advice of this discussion in [exercism/problem-specifications](https://github.com/exercism/problem-specifications/pull/250), I opted to include intermediate methods in the tests here. Having said that, I think there might be quite a wide variety of ways to move from the input text to the ciphertext and these intermediate methods might get in the way of an elegant implementation rather than aiding in the learning process. 

My example solution here cleanses the input string and then maps the characters out into a matrix which makes the 'encoding' process easy. This makes the intermediate methods `plaintext_segments` and `encoded` rather pointless though. Obviously an example solution is just an example, but I'm wondering whether maybe we shouldn't drop the these for those two intermediate methods and just keep the first and last methods?

**Comment by katrinleinweber** [comment]
Sorry! I overlooked this the last 2 months, and won't have spare time in the next few weeks either.

**Comment by jonmcalder** [comment]
Ok no worries. I don't think the approach of the example solution matters too much, but I'd like a 2nd opinion on whether these intermediate methods should be included in the starting snippet (and more importantly whether they should be tested), so will just keep this PR open for now until you can revisit it later.

**Comment by jonmcalder** [comment]
Thanks! So you think it's fine to include the tests for the intermediate methods?

**Comment by katrinleinweber** [comment]
> […] maybe we shouldn't drop these for those two intermediate methods and just keep the first and last methods?

I think those prevented me from finding a solution to the last test, because I duplicated `strsplit()` and `paste()` code into `ciphertext` that basically did the opposite of what that code did in the intermediate methods/functions. OTOH I can't spend a few hours again to work out a better example.

Because I think it's better to have a really tricky puzzle in the track, than not, I'm OK with merging this. Please squash, because the two merges & conflict resolutions were this messy, because I tried the web-editor for a change, not a JSON-validating IDE :-/

**Comment by katrinleinweber** [comment]
Hi @jonmcalder! Do you have any doubts about merging & squashing this?

**Comment by jonmcalder** [comment]
Thanks @katrinleinweber! I must have missed/overlooked this somehow - I'm ok with it since you are. I'm sure we (or others) can refine it at a later stage if need be :-)

**Pull request merged**
