### PR TITLE
Update acronym tests to version 1.7.0

### PR DESCRIPTION
**Pull request by jonmcalder**
Updates based on [problem-specifications/exercises/acronym/canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json)

### CODE REVIEW

**Comment by katrinleinweber** [comment]
Thanks for implementing the upstream update :-) Because the comment can indeed be removed, I updated the variable name, though. If you agree with the new suggestion, I'm fine with merging this.

**Comment by jonmcalder** [comment]
Cool - thanks!

**Comment by katrinleinweber** [comment]
Hi @jonmcalder, I'm not sure whether you squashed or rebased, but this caused a bit of a problem with my local `r:master`. Fix now, no biggie, but I started #118 to discuss our merge strategies in the future. Let's also adhere to [GitHub Flow](https://guides.github.com/introduction/flow/) more and start PRs from another branch than a forked `master`.

**Comment by jonmcalder** [comment]
Sorry I squashed rather than merging since I generally prefer a cleaner history. Is that an issue?

**Comment by katrinleinweber** [comment]
Which tool did you use? GH's web interface should have added a `Co-authored-by` line. 

As I said, not a biggie that co-authorship was omitted a few times, but as the maintainer team growth, I think we should record also small contributions like updates during a review.

**Comment by jonmcalder** [comment]
It was a normal squash and merge via GitHub - nothing special.

**Comment by katrinleinweber** [comment]
Ooops, my bad, sorry! I'm using the [`refined-github` Firefox add-on](https://github.com/sindresorhus/refined-github/#added-features) which adds `Co-authored-by`. I forgot that GitHub itself doesn't m-(

**Comment by jonmcalder** [comment]
Ok - well sorry for inadvertently stripping you of your co-authorship rights for this PR... will try remember for next time 🤣

**Pull request merged**
